### ISSUE TITLE
ERROR with fritzbox-exporter (fritzbox_exporter)

### ISSUE THREAD

**Issue by liebefuroscar** [stefanandres/bms-monitoring-stack#1]
ERROR: The image for the service you're trying to recreate has been removed. If you continue, volume data could be lost. Consider backing up your data before continuing.

**Comment by stefanandres** [comment]
Which image do you mean explicitely?

**Comment by liebefuroscar** [comment]
This is what happens when I do _docker-compose _up_ https://www.youtube.com/watch?v=Ypm1ekYNgwY__

**Comment by stefanandres** [comment]
I think I just missed to link to the https://github.com/ndecker/fritzbox_exporter dependency or automate this. That's the image I used, you can just build this locally. This is why it's also referenced locally.

My Pi where I ran this stuff is shut off currently though, so I cannot check on it directly.

**Comment by liebefuroscar** [comment]
I have tried to install it locally but am not able to. How could I do it?

**Comment by stefanandres** [comment]
if you don't have a fritzbox in your setup, I wouldn't bother to get it running. If you do, you'd have to find yourself a suitable metrics exporter, if you really want one
