### ISSUE TITLE
docker-compose up -d won't build

### ISSUE THREAD

**Issue by mflage** [stefanandres/bms-monitoring-stack#2]
Won't build:

```
Fatal Python error: _Py_InitializeMainInterpreter: can't initialize time
PermissionError: [Errno 1] Operation not permitted

Current thread 0xb6ffb390 (most recent call first):
ERROR: Service 'bms-exporter' failed to build: The command '/bin/sh -c pip install .' returned a non-zero code: 132
```

**Comment by stefanandres** [comment]
I don't give any support for this right now. I've built this hobby project to properly build >1 year ago. 
I am open for a PR if you are willing to get it to build with the recent versions of the current dependencies.

PS: the actual error message is probably above your `pip install failed`
